#!/usr/bin/env bash
cd "$HOME/.config/sublime-text-2/Packages/User"
# git pull origin master
function doIt() {
    rsync --exclude "*.last-run" --exclude ".gitmodules" --exclude "bootstrap.sh" \
        --exclude "README.md" --exclude "*.pyc"  -av --no-perms . $HOME/dotfiles/.config/sublime-text-2/Packages/User
}

if [ "$1" == "--force" -o "$1" == "-f" ]; then
    doIt
else
    read -p "This may overwrite existing files in your dotfile. Are you sure? (y/n) " -n 1
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        doIt
    fi
fi
unset doIt
# source ~/.bash_profile
